language: node_js
node_js:
  - '0.12'
  - '4.2'
deploy:
  provider: npm
  email: mahnunchik@gmail.com
  api_key:
    secure: fGFoD2S5JYeeLNalPNY49Jf7wUW8FNNxPs/2BeSmnikUotE/bzPpIsCrqsW0XyFAtNKjeV9AVI5zE5AKaJcwy2/uGvUK/q7ql3WG+YlIGwXME/HJvAocNql8+RXWBxDKbXXaJ15HSlWEkuTG/ixG2qUpMrZRDXD9EbTBVTOSLJM=
  on:
    tags: true
    repo: mahnunchik/gulp-responsive
